"""Add currency and locale to users

Revision ID: 75e1587d0f3a
Revises: da4db1d0e386
Create Date: 2026-01-06 08:08:29.493463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75e1587d0f3a'
down_revision: Union[str, None] = 'da4db1d0e386'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('currency', sa.String(length=3), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'currency')
    # ### end Alembic commands ###
