"""Add goal_id to transactions

Revision ID: 7f98e3a2e540
Revises: f599d503d4d6
Create Date: 2025-12-16 14:17:04.022606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f98e3a2e540'
down_revision: Union[str, None] = 'f599d503d4d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'savings', ['goal_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'goal_id')
    # ### end Alembic commands ###
