"""Add profile fields

Revision ID: da4db1d0e386
Revises: 7f98e3a2e540
Create Date: 2025-12-21 13:33:50.248683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da4db1d0e386'
down_revision: Union[str, None] = '7f98e3a2e540'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('picture', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('given_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('family_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('locale', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'locale')
    op.drop_column('users', 'family_name')
    op.drop_column('users', 'given_name')
    op.drop_column('users', 'picture')
    # ### end Alembic commands ###
